### PR TITLE
feat(CreateQuestion): ENG-262 new create question form

### PR DESCRIPTION
**Pull request by danielgek**
## 🗃 Story Description

_Link to Shortcut card, if PR is part of a story._

## 🧪 Test Suite
- Navbar Actions
  - [ ] Switch between light and dark mode across pages
  - [ ] Network Switcher
  - [ ] Wrong Network Modal
- Homepage Markets Navigation
  - [ ] Filters
  - [ ] Sorting
  - [ ] Search
- Pages Content
  - [ ] Homepage
  - [ ] Create Market Page
  - [ ] Market Page
  - [ ] Portfolio
- Trading (**Optional** - only if PR involves related components or `polkamarkets-js`)
  - [ ] Slider + MAX button
  - [ ] Buy Outcome Shares
  - [ ] Sell Outcome Shares
  - [ ] Add Liquidity 
  - [ ] Remove Liquidity
 
  ## 📝 Footnotes
  _Noting to add._

### CODE REVIEW

**Review by rsmarques — CHANGES_REQUESTED** [review]
@danielgek outcomes data is being lost when going back to Step 2 from Step 3.

**Comment by danielgek** [comment]
@rsmarques this is fixed and also added the images when you go back on the form

**Comment by rsmarques** [comment]
Looks good @danielgek, just missing a few details:

1. Compilation warnings from eslint
image

2. `•` divider from the liquidity stayed in the previewer
image

**Comment by danielgek** [comment]
@rsmarques all fixed

**Comment by danielgek** [comment]
@rsmarques dont merge this yet as leandro has made some changes

**Review by rsmarques — APPROVED** [review]

**Pull request merged**
